apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ghzh01zv1-go
  janus-idp.io/tekton: ghzh01zv1-go
  backstage.io/kubernetes-id: ghzh01zv1-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ghzh01zv1-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
